default:
  golem_name: SampleSizeR
  golem_version: '0.1'
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/Miller63/Pfizer/Outcomes Reseach Germany - Team only - RM/Portfolio/SampleSizeR
